[mgr]
show_hidden    = true

[opener]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
  #{ run = 'vim --not-a-term "$@"', desc = "vim", block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$1"',                desc = "Open", for = "linux" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
  { run = 'mpv --force-window "$@"', desc = "Play with mpv", orphan = true, for = "unix" },
]
play-only-audio = [
  { run = 'alacritty -t "mpv: $@" -e mpv --no-video "$@"', desc =  "Only audio with mpv", orphan = true, for = "unix" },
]

[open]
rules = [
  # Folder
  { name = "*/", use = [ "edit", "open", "reveal" ] },
  # Text
  { mime = "text/*", use = [ "edit", "reveal" ] },
  # Image
  { mime = "image/*", use = [ "open", "reveal" ] },
  # Media
  { mime = "{audio,video}/*", use = [ "play", "play-only-audio", "reveal" ] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
  { mime = "*/javascript", use = [ "edit", "reveal" ] },
  # Empty file
  { mime = "inode/empty", use = [ "edit", "reveal" ] },
  # Fallback
  { name = "*", use = [ "open", "reveal" ] },
]

[[plugin.augment-command]]
skip_single_subdirectory_on_enter = false
skip_single_subdirectory_on_leave = false
